name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
        with:
           gradle-version: '8.12'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Archive Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: ./build/libs

      - name: Hash Artifacts
        run: |
          for u in *.jar; do
            echo "$(sha256sum "$u")" >> hashes.sha256
          done
        shell: bash
        working-directory: ./build/libs

      - name: Upload Hashes
        uses: actions/upload-artifact@v4
        with:
          name: Hashes
          path: ./build/libs/hashes.sha256
